version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      npm install

artifacts:
  files:
    - config/**/*
    - controllers/**/*
    - models/**/*
    - routes/**/*
    - apidoc.json
    - app.js
    - server.js
    - appspec.yml
    - package.json
    - application_start.sh
    - before_install.sh
    - after_install.sh
    - node_modules/**/*