version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  # build:
  #   commands:
  #     - npm run build
artifacts:
  type : zip
  files:
    - node_modules/**/*
    - package.json
    - server.js
    - appsec.yml
    - application_start.sh
    - before_install.sh